# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GlobalHealth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftyButton'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'FoldingCell'
    pod 'TwilioVoice', '3.0.0-preview4'
    pod 'RealmSwift'
    pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  # Pods for GlobalHealth

end
